base_url = "http://localhost:1111"
title = "Minima for Gutenberg"
description = "A fork of the default Jekyll theme to Gutenberg"

compile_sass = true
highlight_code = true
build_search_index = false
generate_rss = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true}
]

[extra]
# Put all your custom variables here
